version: "3.7"

services:
  parrot:
    container_name: parrot
    image: willfantom/parrot.live
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - PARROT_REDIRECT=${REDIRECT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.parrot.rule=Host(`parrot.${DOMAIN}`)
      - traefik.http.services.parrot.loadbalancer.server.port=3000
      - traefik.http.routers.parrot.middlewares=basic
      - traefik.http.routers.parrot.tls=true
      - traefik.http.routers.parrot.tls.certresolver=tlsc

networks:
  traefik-network:
    external: true
  default:
    driver: bridge
