version: '3.7'

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    user: root
    networks:
      - default
      - traefik-network
    volumes:
      - ${PROMETHEUS_CONFIG_DIR}:/etc/prometheus/
      - ${PROMETHEUS_DATA_DIR}:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    labels:
      - traefik.enable=true
      - traefik.http.routers.prom.entrypoints=websecure
      - traefik.http.routers.prom.rule=Host(`prom.${DOMAIN}`)
      - traefik.http.services.prom.loadBalancer.server.port=9090
      - traefik.http.routers.prom.middlewares=bauth,basic
      - traefik.http.routers.prom.tls=true
      - traefik.http.routers.prom.tls.certresolver=cfdns

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: unless-stopped
    networks:
      - default
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  alertmanager:
    container_name: prometheus-alert-manager
    image: prom/alertmanager
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ${ALERT_MANAGER_CONFIG}:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    restart: unless-stopped
    networks:
      - default
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  traefik-network:
    external: true
  default:
    driver: bridge
