version: "3.7"

services:

  gotify:
    container_name: gotify
    image: gotify/server:latest
    restart: unless-stopped
    networks:
      - traefik-network
    volumes:
      - ${GOTIFY_DATA}/data:/app/data
    environment:
      - GOTIFY_DATABASE_DIALECT=sqlite3
      - GOTIFY_DATABASE_CONNECTION=gotify.db
      - GOTIFY_DEFAULTUSER_NAME=${USERNAME}
      - GOTIFY_DEFAULTUSER_PASS=${PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.gotify.entrypoints=websecure
      - traefik.http.routers.gotify.rule=Host(`gotify.${DOMAIN}`,`notify.${DOMAIN}`)
      - traefik.http.services.gotify.loadBalancer.server.port=80
      - traefik.http.routers.gotify.middlewares=basic
      - traefik.http.routers.gotify.tls=true
      - traefik.http.routers.gotify.tls.certresolver=cfdns

networks:
  traefik-network:
    external: true
  default:
    driver: bridge